In [1]:
import sys
sys.path.append('../../')
from utils import read_txt_to_mot, convert_pickled_to_txt

detections = convert_pickled_to_txt('/mnt/c/workspace/outputs/frcnn_r18_hdet640-cam3_1hour_1.pkl', return_df=True)
detections

,0,1,2,3,4,5,6,7,8,9
0,1,-1,530.346313,509.484558,114.661255,141.309082,0.997401,-1,-1,-1
1,1,-1,1251.993530,413.828430,27.150146,191.169189,0.084728,-1,-1,-1
2,1,-1,1263.261475,748.944397,15.646484,91.564331,0.081935,-1,-1,-1
3,1,-1,1264.300537,418.383514,15.276123,99.041168,0.077154,-1,-1,-1
4,1,-1,1247.036255,861.161926,32.944824,98.203369,0.075162,-1,-1,-1
...,...,...,...,...,...,...,...,...,...,...
361691,14952,-1,812.116760,256.273895,115.758179,116.298767,0.996645,-1,-1,-1
361692,14952,-1,352.774597,0.981041,167.978760,147.855591,0.998795,-1,-1,-1
361693,14952,-1,952.257812,231.689972,99.287598,139.003113,0.050106,-1,-1,-1
361694,14952,-1,821.579468,361.355865,205.232422,190.212982,0.088632,-1,-1,-1
361695,14952,-1,0.235830,945.865540,45.538025,14.112549,0.050102,-1,-1,-1

In [3]:
from sort import get_sort_results
get_sort_results(detections)

In [4]:
import pandas as pd

pd.read_csv('../../sample/feats_frcnn_r50/resnext50_32x4d_swsl/detections.csv')

,index,frame_id,track_id,x1,y1,w,h,confidence,na1,na2,na3,feat
0,0,1,-1,816.85657,253.892910,133.919430,129.941100,0.998455,-1,-1,-1,/home/ted/workspace/tracking/TedTrack/sample/f...
1,1,1,-1,1234.93120,918.448360,44.980225,41.168090,0.056022,-1,-1,-1,/home/ted/workspace/tracking/TedTrack/sample/f...
2,2,1,-1,202.22534,333.269040,150.100830,123.737430,0.066251,-1,-1,-1,/home/ted/workspace/tracking/TedTrack/sample/f...
3,3,1,-1,1267.88850,883.439200,12.059570,75.524170,0.076428,-1,-1,-1,/home/ted/workspace/tracking/TedTrack/sample/f...
4,4,1,-1,200.89758,281.310800,102.948330,92.303406,0.125700,-1,-1,-1,/home/ted/workspace/tracking/TedTrack/sample/f...
...,...,...,...,...,...,...,...,...,...,...,...,...
184196,184196,14952,-1,1258.36790,940.829040,21.531006,19.054321,0.272726,-1,-1,-1,/home/ted/workspace/tracking/TedTrack/sample/f...
184197,184197,14952,-1,1265.52050,918.263240,14.384766,41.149536,0.172149,-1,-1,-1,/home/ted/workspace/tracking/TedTrack/sample/f...
184198,184198,14952,-1,246.98550,746.694300,81.854675,113.301510,0.120508,-1,-1,-1,/home/ted/workspace/tracking/TedTrack/sample/f...
184199,184199,14952,-1,228.45770,830.419860,88.421326,86.185180,0.107055,-1,-1,-1,/home/ted/workspace/tracking/TedTrack/sample/f...
184200,184200,14952,-1,0.06695,78.129395,50.934135,137.345520,0.081312,-1,-1,-1,/home/ted/workspace/tracking/TedTrack/sample/f...